name: hackathon5G
channels:
  - conda-forge
dependencies:
  # general
  - python=3.10
  - jupyterlab=3
  # specific
  - pandas=2.0.1
  - numpy=1.22.4
  - scikit-learn=1.2.2
  - seaborn=0.12.2
  - plotly=5.14.1
